# Nombre del flujo de trabajo
name: Build and Deploy to Google Cloud Run

# Desencadenar automáticamente el flujo de trabajo
on:
  # Activador del flujo de trabajo
  push:
    branches:
      - "main"
    
# Varibles 
env:
  PROJECT_ID: openmarket-demo # TODO: update Google Cloud project id
  GAR_LOCATION: europe-southwest1
  SERVICE: srv-usuario-pg-cloud  
  SERVICE_ACCOUNT: servicios-generales@openmarket-demo.iam.gserviceaccount.com
  REGION: europe-southwest1 
  REPOSITORY: usuario-repo-pg-cloud
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_PROJECT_KEY: userdemo-git-pg-cloud  

# Trabajos que se ejecutan en el flujo de trabajo
# Trabajos que se ejecutan en el flujo de trabajo
jobs:
  buildPush:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    
    # Configura el job para que se ejecute en la versión más reciente de un ejecutor Ubuntu Linux. 
    runs-on: ubuntu-latest
    # Agrupa todos los pasos que se ejecutan en el trabajo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: List repository
        id: listrepo           
        run: |-
          echo "::set-output name=num_rep::$(gcloud artifacts repositories list --location=europe-southwest1 --filter="REPOSITORY~noesta")"
      - name: Check list
        run: echo ${{ steps.listrepo.outputs.num_rep }}
          
      - name: List repository 2
        id: listrepo2           
        run: |-
          echo "::set-output name=num_rep_t::$(gcloud artifacts repositories list --location=europe-southwest1 --filter="REPOSITORY~${{ env.REPOSITORY }}")"
          
      - name: Check list 2
        run: echo ${{ steps.listrepo2.outputs.num_rep_t }}
          
      - name: Create Repository
        continue-on-error: true
        run: |-
         gcloud artifacts repositories create ${{ env.REPOSITORY }} --repository-format=docker --location=${{ env.REGION }} --description="Repositorio servicio usuario pg"

      # Configurar la autenticación en los repositorios de Docker en la región      
      - name: Docker Auth
        run: |-       
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin europe-southwest1-docker.pkg.dev
          #   gcloud auth configure-docker europe-southwest1-docker.pkg.dev --quiet
   
      #- name: Build Container
      #  run: |-
      #   docker build --build-arg SONAR_LOGIN=${{ env.SONAR_TOKEN }} --build-arg SONAR_HOST=${{ env.SONAR_HOST_URL }} --build-arg SONAR_PROJ=${{ env.SONAR_PROJECT_KEY }} -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
      # docker build --build-arg SONAR_LOGIN=075a8f98ef594014eb3fdc6169165f7c6cd1fabb --build-arg SONAR_HOST=http://34.175.69.230:9000 --build-arg SONAR_PROJ=userdemo-git-pg-cloud -t "userDemo:0.1" ./
        
      - name: Build and Push 
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            SONAR_LOGIN=${{ env.SONAR_TOKEN }}
            SONAR_HOST=${{ env.SONAR_HOST_URL }}
            SONAR_PROJ=${{ env.SONAR_PROJECT_KEY }}
          push: true
          tags: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
         
      #- name: Push Container
      #  run: |-      
      #   docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
      
  deploy:
    needs: buildPush
     # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    
    steps:
       - name: Google Auth
         id: auth
         uses: 'google-github-actions/auth@v0'
         with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

       - name: Deploy
         run: |-
          gcloud run deploy ${{ env.SERVICE }} --image="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" --project=${{ env.PROJECT_ID }} --port=8080 --region=${{ env.REGION }} --allow-unauthenticated --max-instances=29